### ISSUE TITLE
code stuck at "self.npc = manager.NeuralPointCloud(cfg)"

### ISSUE THREAD

**Issue by Yiiii19** [eriksandstroem/Point-SLAM#13]
Hi, when i want to run the code for replica dataset, the code was stuck at `Point_LAM.py`
`self.npc = manager.NeuralPointCloud(cfg)`
It happened a few times. At one time it runs successfully.
Do you have any solution or idea about that?
Thanks!

**Comment by eriksandstroem** [comment]
Hi @Yiiii19,
Sadly, we did not encounter this issue you describe. Typically when code gets stuck like this, it can be RAM related. If you are using a cluster, you can perhaps try to request a bit more RAM and see if it makes a difference.

**Comment by StarryN** [comment]
This issue is likely caused by specifying the GPU ID = 0 during the initialization of the neural points. If your GPU is randomly assigned by the server, it may cause faiss to become unresponsive.
The solution is to change the code from:
https://github.com/eriksandstroem/Point-SLAM/blob/5bd918d70c10497d2369fd2e86bba792ea959d50/src/neural_point.py#L14
to `self.cuda_id = torch.cuda.current_device()`

**Comment by Rashfu** [comment]
same problem here. Couldn't run the code on 3090GPU
