### ISSUE TITLE
Hello, as a newcomer, I do not understand some of the sentences in the paper, could you please answer it for me?

### ISSUE THREAD

**Issue by eggman-1024** [eriksandstroem/Point-SLAM#21]
1."For each sampled pixel we sample a set of points xi along the ray and extract the geometric and color features (P g(xi) and P c(xi) resp.)" 
Are the geometric and color features here initially randomized?

2."at xi, using feature interpolation within the spherical search radius r"
Why do we need feature interpolation? My understanding is that the original sampling is sparse point cloud, which is not enough to restore the scene, so feature interpolation is used to construct dense point cloud to restore the scene. Is my understanding correct?

**Comment by eggman-1024** [comment]
“If no neighbors are found, we add three neural points along the ray, centered at the depth reading D and then offset by (1−ρ)D and (1+ρ)D with ρ ∈ (0, 1) being a hyperparameter accounting for the expected depth noise”
I'm sorry this may disturb you, what is the effect of adding three points to the ray if no point in the neighborhood can be found? I don't quite understand the expected depth noise mentioned here. And, with or without neighbors, isn't there already a sampling point at D? Why do we add sampling points at D? Look forward to your answer, thank you!

**Comment by eriksandstroem** [comment]
1. Correct. They are initially randomly sampled from a normal distribution.
2. I think your understanding is correct. Let me clarify. The point cloud we use is neither dense nor sparse, but dynamically adapting based on the need to store information. Where there is lots of texture details, we have a higher point density. We sample the points xi anywhere in space and even if we have a dense point cloud, we need to interpolate to get the feature value at exactly xi. 
3. If no neighbors are found, we realize that we need to add points there to reconstruct that part of the scene - this is "the effect". The idea behind the depth dependency here is that pixels with a larger absolute depth are more likely to be noisy so we can not trust the depth reading to the same degree. Therefore we spread out the points more such that we have larger band in which the surface can be optimized (i.e. it correlates with the expected std of the sensor). Hope this helps. You ask "isn't there already a sampling point at D?" I am not exactly sure what you mean by this. To clarify: just because we sample at D does not mean that there is already a point in the neural point cloud there. Therefore, we need to check this - if there are already points there, we don't need to add new ones, and otherwise we add new points. 

Let me know if things are still unclear.

**Comment by eggman-1024** [comment]
Thank you for your answer! I have another question: “we sample X pixels uniformly across the image plane and Y pixels among the top 5Y pixels with the highest color gradient magnitude.”. Is the pixel here a neural point? However, below Figure 2 "For each sampled pixel we sample a set of points xi along the ray", it is explained that a set of nerve points is sampled for each pixel in the direction of light. These two explanations mystify me.

**Comment by eriksandstroem** [comment]
The pixel here is not a neural point, but a pixel in the image. 

There are two stages of sampling points in 3D: 1. Sampling pixels in the image plane through which rays are shot i.e. "we sample X pixels uniformly across the image plane and Y pixels among the top 5Y pixels with the highest color gradient magnitude". 2. We sample 3D points along the rays going through the pixels (from the camera center) i.e. ""For each sampled pixel we sample a set of points xi along the ray".

Hope that helps!

**Comment by eggman-1024** [comment]
Thank you very much!
