### ISSUE TITLE
Map density

### ISSUE THREAD

**Issue by almorav** [eriksandstroem/Point-SLAM#29]
Hi! I am following your running tutorial and I was able to get some results on the provided datasets. However, I was wondering if there is a way in which I can increase the number of points in the final point cloud. Is there any parameter that I can modify so that point density in the final map increases?

This is the map that I obtain in the freiburg1_desk scenario using Point-SLAM:
![Captura de pantalla de 2024-03-08 09-20-37](https://github.com/eriksandstroem/Point-SLAM/assets/106400258/014c40fd-249b-4575-bd74-22cf47886c13)

And this is the one that I obtain with NICE-SLAM:
![Captura de pantalla de 2024-03-08 09-22-12](https://github.com/eriksandstroem/Point-SLAM/assets/106400258/4fd8c338-b2bf-436f-a36e-b9599efc01fb)

Thank you in advance for your time!

**Comment by eriksandstroem** [comment]
Hi,
Indeed, the point cloud is by design not so dense to save on memory. You can read about the dynamic point density in the paper. To increase the density, you can easily do this by changing the maximum and minimum search radius in the config file.  I would suggest putting the maximum to 2 cm i.e. this parameter and try again https://github.com/eriksandstroem/Point-SLAM/blob/main/configs/point_slam.yaml#L114
