### ISSUE TITLE
Align points on each frame with the corresponding points in the point cloud

### ISSUE THREAD

**Issue by Drapandiger** [eriksandstroem/Point-SLAM#33]
Hello, I want to ask whether it is possible to align the points in each frame with the corresponding points in the point cloud. I would try to label every points with semantic information

**Comment by eriksandstroem** [comment]
Hi!
Yes, this is straight forward since we add new neural points by unprojecting the pixel depths to 3D. We do not currently store this information as part of the neural point cloud but you can easily store the frame index and pixel coordinate for each neural point as auxiliary information if you want. In ScanNet and Replica, the ground truth semantic information is already labeled, but we do not use it.

Hope that helps!
Erik
